package jp_2dgames.game.gui.message;
class Msg {
  public static inline var DAMAGE_PLAYER:Int  = 1;  // プレイヤーへのダメージ
  public static inline var DAMAGE_ENEMY:Int   = 2;  // 敵へのダメージ
  public static inline var ATTACK_BEGIN:Int   = 3;  // 攻撃開始
  public static inline var DEFEAT_ENEMY:Int   = 4;  // 敵を倒した
  public static inline var DEAD:Int           = 6;  // 死亡
  public static inline var ITEM_USE:Int       = 7;  // アイテムを使った
  public static inline var RECOVER_HP:Int     = 8;  // HP回復
  public static inline var ESCAPE:Int         = 9;  // 逃走開始
  public static inline var ITEM_GET:Int       = 11; // アイテム入手
  public static inline var ITEM_CANT_GET:Int  = 12; // アイテムを入手できない
  public static inline var ITEM_DEL_GET:Int   = 13; // アイテムを捨てて拾う
  public static inline var ITEM_ABANDAN:Int   = 14; // アイテムをあきらめる
  public static inline var ITEM_SEL_DEL:Int   = 15; // 捨てるアイテムを選択
  public static inline var ATTACK_MISS:Int    = 20; // 攻撃回避
  public static inline var PLAYER_DEAD:Int    = 22; // プレイヤー死亡
  public static inline var BST_POISON:Int     = 23; // バステ: 毒
  public static inline var BST_CONFUSION:Int  = 24; // バステ: 混乱
  public static inline var BST_CLOSE:Int      = 25; // バステ: 封印
  public static inline var BST_PARALYZE:Int   = 26; // バステ: 麻痺
  public static inline var BST_SLEEP:Int      = 27; // バステ: 眠り
  public static inline var BST_BLIND:Int      = 28; // バステ: 盲目
  public static inline var BST_CURSE:Int      = 29; // バステ: 呪い
  public static inline var BST_WEAK:Int       = 30; // バステ: 衰弱
  public static inline var BST_STAN:Int       = 31; // バステ: スタン
  public static inline var STANING:Int        = 32; // スタン中
  public static inline var ITEM_BUY:Int       = 43; // アイテム購入
  public static inline var ITEM_DEL:Int       = 45; // アイテムを捨てる
  public static inline var GROW_HPMAX:Int     = 46; // 最大HP上昇
  public static inline var ITEM_CANT_BUY:Int  = 52; // アイテム所持数が最大数に達しているので買えない
  public static inline var ACTION_STANDBY:Int = 53; // 何もしない
  public static inline var ENEMY_APPEAR:Int   = 54; // 敵出現
  public static inline var FIND_NEXTFLOOR:Int = 55; // 次のフロアへ進む道を見つけた
  public static inline var ITEM_DESTROY:Int   = 56; // アイテム破壊
  public static inline var FOOD_ADD:Int       = 57; // 食糧が増えたよ
  public static inline var REST:Int           = 58; // 休憩した
  public static inline var SEARCHING:Int      = 59; // 探索中……
  public static inline var ITEM_FIND:Int      = 60; // アイテムを見つけた
  public static inline var NOTHING_FIND:Int   = 61; // 何も見つからなかった
  public static inline var WEAPON_POWERUP:Int = 62; // 武器強化
  public static inline var ARMOR_POWERUP:Int  = 63; // 防具強化
  public static inline var JUST_ZERO_BONUS:Int= 64; // ジャストゼロボーナス
  public static inline var AUTO_ATTACK:Int    = 65; // 自動攻撃
  public static inline var UPGRADE_PARAM:Int  = 66; // ステータス強化
  public static inline var UPGRADE_HPMAX:Int  = 67; // 最大HP上昇
  public static inline var LAST_ATTACK:Int    = 68; // 最後の一撃
  public static inline var FOOD_NOTHING:Int   = 69; // 食糧がなくなった
  public static inline var HUNGRY_DAMAGE:Int  = 70; // 空腹ダメージ
  public static inline var DEX_UP:Int         = 71; // 命中率上昇
  public static inline var EVA_UP:Int         = 72; // 回避率上昇
  public static inline var NOT_ENOUGH_MONEY   = 73; // お金が足りない
}
